### PR TITLE
Revert "Remove libbfqio"

### PR DESCRIPTION
**Pull request by NRanjan-17**
This reverts commit 010873d87913cee16e5b7233b64509f160e8cfff.

### CODE REVIEW

**Comment by Darkstar085** [comment]
Why..???

**Comment by NRanjan-17** [comment]
not working for mido and more devices without it

**Comment by Darkstar085** [comment]
Everything works just adapt according to it..

**Comment by NRanjan-17** [comment]
https://cirrus-ci.com/build/6249849136873472
check this

**Comment by Darkstar085** [comment]
Update hals bruh ..

**Comment by NRanjan-17** [comment]
latest hals

**Comment by Darkstar085** [comment]
> latest hals

Give

**Comment by NRanjan-17** [comment]
leave it

**Comment by Darkstar085** [comment]
K leaving..

**Pull request closed without merging**
